version: "3.7"
services:
  spark-master:
    image: adbadb/spark-master:3.5.1
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: adbadb/spark-worker:3.5.1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=256m
      - SPARK_EXECUTOR_MEMORY=512m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data